### PR TITLE
ember-cli es6 [part II]

### PR DESCRIPTION
**Pull request by miguelcobain**
- [x] updated tests to conform the latest ember-cli (@twokul please fix my custom helper registration workaround)
- [x] added the remaining path layers
- [x] update README
- [ ] port remaining tests from master
- [ ] migrate source code comment docs (I didn't touch them. what will be our strategy here? A class reference is really important for Ember Leaflet since people are likely to extend our classes. Maybe this addon would be useful: https://github.com/cibernox/ember-cli-yuidoc)
- [ ] is there a better way we could include leaflet **without** polluting global namespace (`L`) ?

### CODE REVIEW

**Comment by miguelcobain** [comment]
Testing the ember-leaflet component was easy. Ember-cli already provides blueprints for testing components. But what would be a good way to test our layer classes?
They're just regular Ember classes, but in order to test them we require an EmberLeaflet component to be created first.

**Comment by gabesmed** [comment]
Yeah I knowm there aren't really any good unit tests for the layers. Instead everything's a full functional test including Leaflet functionality.

The right way to do this would be to mock out the Leaflet library and the EmberLeaflet component, and just make sure the layer class makes the right function calls.

But practically, I still think we'd want a full set of functional tests to also ensure that the integration stays working, especially for when we upgrade ember versions, leaflet versions, etc.

So not sure what to do here -- if people have a lot of time, we could explore re-writing the tests. But the fastest way through the es6 module conversion I think would be keep the functional test suite as-is, and improve the test methodology after the conversion is done?

**Comment by miguelcobain** [comment]
I'm not really talking about the previous tests. They're totally fine!

I just not sure about the best way to port those tests, i.e the test "template" to use.
Our layer classes don't fall into any of ember-cli's class "stereotypes". But I guess a simple test will do.

**Comment by miguelcobain** [comment]
ping @twokul 

You must be busy at EmberConf, but if you find some minutes to put up an example layer test in this PR I could easily try to port the remaining tests according to your input.

**Comment by ethanharstad** [comment]
Just came across this and wanted to point out that Leaflet 0.8 is now an AMD module. You can also use L.noConflict() to remove the global. There is a little bit of discussion about leaflet and EAK here https://github.com/Leaflet/Leaflet/pull/1778 as well.

**Comment by twokul** [comment]
@miguelcobain will look into this tonight

**Comment by twokul** [comment]
I have no idea what just happened.

**Pull request merged**
