### PR TITLE
Update ember-cli 0.2.3

### PR DESCRIPTION
**Pull request by miguelcobain**

### CODE REVIEW

**Comment by miguelcobain** [comment]
@gabesmed The results of ember-try are:
```
------ RESULTS ------

ember-1.10: PASS
ember-1.11.0: FAIL
ember-1.12.0-beta.1: FAIL
```

The tests that are failing are related with poup mixin (again :cry:).
Can you please take a look?

**Comment by AW-UC** [comment]
Maybe caused by https://github.com/ember-cli/ember-cli/issues/3863? Next version of ember-cli will revert to old `router.js`. So perhaps just skip that version?

**Comment by miguelcobain** [comment]
The tests that are failing are related to the PopupMixin.
I think it isn't at all related to Ember's router. We use a few private API's in PopupMixin. That may be the culprit.

**Comment by miguelcobain** [comment]
Bam, fixed.

**Pull request merged**
