### PR TITLE
[WIP] Make leaflet component extensible

### PR DESCRIPTION
**Pull request by AW-UC**
This makes the Leaflet component extensible, by doing the following:

- It gives the component a different name than the addon to prevent namespace conflicts (e.g. https://github.com/gabesmed/ember-leaflet/issues/68)
- All of the actual logic of the components, layers etc. is moved to the addon tree
- Only a wrapper module of the component is merged with the hosting app, which is easily extensible (see guideline here: http://ember-cli-docs.divshot.io/docs/developing-addons-and-blueprints/)
- update tests
- update README

### CODE REVIEW

**Comment by miguelcobain** [comment]
I've been trying to do this for a long time, thank you!
I'll just take a closer look today, but it seems really fine.

Appreciated.

**Comment by AW-UC** [comment]
I'll have a look at the tests.
For now, I included wrappers for all the modules, but I think it will also be sufficient, if we only have a wrapper for the component.
What do you think about renaming the component? I think it should have a different name than the addon. I came up with `leaflet-map`, but if you prefer another name, just let me know.

**Comment by miguelcobain** [comment]
I love it. Maybe @gabesmed and @twokul have something to say here, but for me it's great.

**Comment by AW-UC** [comment]
All failing tests that are related to this PR are fixed.

**Comment by miguelcobain** [comment]
Are you sure? Looks like Travis is still complaining.

**Comment by miguelcobain** [comment]
@AW-UC can you include the latest changes from PR #106 in this PR?

**Comment by AW-UC** [comment]
@miguelcobain included latest chages. With tests fixed I meant all real issues besides JSHint complaints. Anyway, I also fixed the JSHint issues, even if they are not really related to this PR. Will squash commits.

**Comment by miguelcobain** [comment]
@AW-UC this is perfect!
We're almost ready to get this on the master branch and publish the addon.

**Comment by jwo** [comment]
@AW-UC Kudos to you! Very awesome.

**Comment by AW-UC** [comment]
Updated README. I guess this is done now. Any objections against not squashing the commits? I know it is not very tidy, but I did a rebase between the commits that are to be squashed. Not sure how to do this painlessly.

**Comment by AW-UC** [comment]
@miguelcobain just saw your question here: https://github.com/gabesmed/ember-leaflet/pull/107#issuecomment-94795138
Yes, you can still import like that. The component wrapper is only there, so that your app will always have at least the defaul component registered (so something happens out of the box if you call `{{leaflet-map}}`). It doesn't make sense to register the other stuff, because it can be imported wherever it is needed.

**Pull request merged**
