### PR TITLE
GeoJSON layer

### PR DESCRIPTION
**Pull request by mdebbar**

### CODE REVIEW

**Comment by miguelcobain** [comment]
Thanks for the PR.
I'm afraid that we will need some tests for this to get accepted?

Side note: have you checked [ember-leaflet 2](http://www.ember-leaflet.com/)?

**Comment by mdebbar** [comment]
I'll add some tests soon. The link doesn't show anything?

**Comment by miguelcobain** [comment]
forgot to add protocol. :stuck_out_tongue:

Updated.

**Comment by mdebbar** [comment]
Oh that. I've seen it several days ago. I like that I can use it directly in my template, declaratively. But we are already using `gabesmed/ember-leaflet`. Do you recommend moving to the new one?

**Comment by miguelcobain** [comment]
@mdebbar definitely. It has a number of advantages.

**Pull request closed without merging**
