### PR TITLE
Fix ember 1.12 deprecations

### PR DESCRIPTION
**Pull request by AW-UC**
This makes some minor adjustments for Ember 1.12, introduced with Ember CLI 0.2.4. The new get/set code is a breaking change, which will not work in Ember CLI < 0.2.4. So it is probably best to not merge this immediately.

### CODE REVIEW

**Comment by miguelcobain** [comment]
We should use https://github.com/rwjblue/ember-new-computed which polyfills this functionality to work across all ember versions.
Uses native Ember.computed new syntax if available.

**Comment by AW-UC** [comment]
yes, that is an definately option. however, it hasn't been updated to the latest syntax which is e.g. `get(key){}` instead of `get: function(key){}`. This is a little bit confusing but probably no real issue.

**Comment by miguelcobain** [comment]
`get(key){}` is the ES6 equivalent of `get: function(key){}`. They are completely interchangeable.
As long as ember uses Babel, `get(key){}` is valid as well.

This PR can be converted to use this polyfill very easily.

**Comment by AW-UC** [comment]
allright, then we probably should do the changes to `package.json` first.

**Comment by miguelcobain** [comment]
Steps:
- `$ ember install ember-new-computed`
- Use `import computed from 'ember-new-computed';`
- Use `computed(...)` instead of `Ember.computed(...)`

If you could add this to this PR I could merge this.

**Comment by AW-UC** [comment]
Do you think, it will be a problem if I rename the `computed` array in `computed.js` to something else? Because, I am already importing the module as `computed` and would like to avoid something similar to `import computed as polyfill from 'ember-new-computed'`.

**Comment by miguelcobain** [comment]
I think its fine. :+1:

**Comment by miguelcobain** [comment]
Not sure why these two tests are failing.

**Comment by AW-UC** [comment]
me neither. the nesting is not that deep, compared to the other functions. one could probably silent the test, by increasing maxDepth, but maybe there is a way to refactor this.

**Comment by AW-UC** [comment]
Ok, seems like `optionProperty` and `pathStyleProperty` are not tested at all regarding their nesting.

**Comment by miguelcobain** [comment]
Is it failing on your local `$ ember test`?

**Comment by AW-UC** [comment]
yes, it's failing here. so, at least I have a chance to debug ;-)

**Comment by miguelcobain** [comment]
Looks like the correct syntax is `set(key, value) {` and not `set(value) {`?

**Comment by AW-UC** [comment]
yeah, sure! how could I miss that. I already used it correctly in that file!

**Comment by miguelcobain** [comment]
Thanks a lot!

**Pull request merged**
